xflags::xflags! {
    src "./src/cmd/flags.rs"

    cmd cmd {
        /// Print version information
        optional --version

        /// Bootstrap dotfiles
        cmd bootstrap {
            repeated args: String
        }

        /// Release/update cmd binary
        cmd release {
            repeated args: String
        }

        /// Configure dotfiles (alias: cfg)
        cmd config cfg {
            repeated args: String
        }

        /// Google Cloud operations
        cmd gcloud {
            repeated args: String
        }

        /// Secret operations
        cmd secret {
            repeated args: String
        }

        /// Terraform (alias: tf)
        cmd terraform tf {
            repeated args: String
        }

        /// Vault operations
        cmd vault {
            repeated args: String
        }

        /// Generate code/files (alias: gen)
        cmd generate gen {
            repeated args: String
        }
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Cmd {
    pub version: bool,
    pub subcommand: CmdCmd,
}

#[derive(Debug)]
pub enum CmdCmd {
    Bootstrap(Bootstrap),
    Release(Release),
    Config(Config),
    Gcloud(Gcloud),
    Secret(Secret),
    Terraform(Terraform),
    Vault(Vault),
    Generate(Generate),
}

#[derive(Debug)]
pub struct Bootstrap {
    pub args: Vec<String>,
}

#[derive(Debug)]
pub struct Release {
    pub args: Vec<String>,
}

#[derive(Debug)]
pub struct Config {
    pub args: Vec<String>,
}

#[derive(Debug)]
pub struct Gcloud {
    pub args: Vec<String>,
}

#[derive(Debug)]
pub struct Secret {
    pub args: Vec<String>,
}

#[derive(Debug)]
pub struct Terraform {
    pub args: Vec<String>,
}

#[derive(Debug)]
pub struct Vault {
    pub args: Vec<String>,
}

#[derive(Debug)]
pub struct Generate {
    pub args: Vec<String>,
}

impl Cmd {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end

impl Cmd {
    pub fn help() -> &'static str {
        Cmd::HELP_
    }
}

