live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors.bright]
black = "#676767"
blue = "#69d8f2"
cyan = "#5ffdff"
green = "#a7e400"
magenta = "#c930c7"
red = "#ef286f"
white = "#feffff"
yellow = "#dfdc58"

[colors.normal]
black = "#333333"
blue = "#69d8f2"
cyan = "#00c5c7"
green = "#a7e400"
magenta = "#c930c7"
red = "#ef286f"
white = "#c7c7c7"
yellow = "#f1993a"

[colors.primary]
background = "#262525"
foreground = "#c7c7c7"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "RecMonoDuotone Nerd Font Mono"
style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B]"
key = "RBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002["
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "}"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "L"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "{"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "H"
mods = "Shift|Command"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002k"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002$"
key = "Period"
mods = "Command"

[[keyboard.bindings]]
key = "Space"
mods = "Shift|Control"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u0017"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
startup_mode = "Windowed"

[window.padding]
x = 2
y = 0
