#!/bin/sh

# exit on error
set -e

# Install nix
if [ ! -x "$(command -v nix-env)" ] && [ $(uname) != "Darwin" ]; then
    curl -L https://nixos.org/nix/install | sh -s -- --daemon
    source "$HOME/.nix-profile/etc/profile.d/nix.sh"
fi

# unset RUSTC_WRAPPER if sccache is not installed
if [ ! -x "$(command -v sccache)" ]; then
    unset RUSTC_WRAPPER
fi

if [ ! -x "$(command -v cc)" ]; then
    echo "Installing git..."
    nix-env -i gcc
fi

# Install Rust
if [ ! -x "$(command -v cargo)" ]; then
    echo "Installing Rust..."
    echo "HOME is $HOME"

    export CARGO_HOME=$HOME/.cargo
    export RUSTUP_HOME=$HOME/.rustup
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init.sh
    sh rustup-init.sh -y --no-modify-path --default-toolchain stable
    rm rustup-init.sh
    source "$HOME/.cargo/env"
fi

cd cmd
mkdir -p secrets
./release

$HOME/.local/bin/cmd bootstrap
sudo chsh $(whoami) --shell $(which zsh)

gpgconf --kill gpg-agent || true
gpgconf --launch gpg-agent || true

exec zsh
