#!/bin/bash

# remove proxmox enterprise repo
rm /etc/apt/sources.list.d/pve-enterprise.list || true

# look for enterprise repos
grep -R "enterprise.proxmox.com" /etc/apt/sources.list.d/

# comment out all of those lines in one go:
for f in /etc/apt/sources.list.d/*.list; do
  sed -i '/enterprise.proxmox.com/s/^/# /' "$f"
done

# verify there are no remaining enterprise entries:
grep -R "enterprise.proxmox.com" /etc/apt

# add no subscription repos
cat <<EOF >/etc/apt/sources.list.d/pve-no-subscription.list
deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
deb http://download.proxmox.com/debian/ceph-quincy bookworm main
EOF

