[misc]
only = [
    "vim",
    "node",
    "custom_commands",
    "rustup",
    "brew_formula",
    "brew_cask",
    "gcloud",
]

[commands]
"Update Cargo tools" = "cargo install-update --all --cooldown 7d --locked"
