#!/bin/sh

set -e

. $HOME/.cargo/env
cargo build --release

BIN_DIR="$HOME/.local/bin"
BIN="$BIN_DIR/cmd"
OLD_BIN="$BIN.old"
NEW_BIN="target/release/cmd"

mkdir -p "$BIN_DIR"

if [ -e "$BIN" ]; then
    mv "$BIN" "$OLD_BIN"
fi

if ! cp "$NEW_BIN" "$BIN"; then
    if [ -e "$OLD_BIN" ]; then
        mv "$OLD_BIN" "$BIN"
    fi
    exit 1
fi

rm -f "$OLD_BIN"
