#!/bin/sh

set -e

. $HOME/.cargo/env
cargo build --release

mkdir -p $HOME/.local/bin
# unlink first so we can overwrite even if the binary is currently running (macOS ETXTBSY)
rm -f $HOME/.local/bin/cmd
cp target/release/cmd $HOME/.local/bin/cmd
