-- local opts = {
--     suggestion = {
--         copilot_model = "gpt-4o-copilot",
--         enabled = true,
--         auto_trigger = true,
--         keymap = {
--             accept = "<C-l>",
--             accept_word = "<C-y>",
--             accept_line = false,
--             next = "<C-s>",
--             prev = "<C-a>",
--             dismiss = "<C-]>",
--         },
--     },
-- }
--
-- return {
--     -- "zbirenbaum/copilot.lua",
--     "AntoineGS/copilot.lua",
--     branch = "gpt4o",
--     cmd = "Copilot",
--     event = "InsertEnter",
--     opts = opts,
-- }
--
return {}
